apiVersion: v1
kind: Service
metadata:
  name: pharmacy-claims-processor-service
spec:
  selector:
    app: pharmacy-claims-processor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer